Repository Kareadita/Kavita, pull requests merged in 2021-08, with the labels that each got.

#467 Updating docker workflow
  .github/workflows/nightly-docker.yml
  .github/workflows/sonar-scan.yml
Labels: enhancement

#471 Updating Docker Workflow
  .github/workflows/sonar-scan.yml
Labels: enhancement

#512 Bugfix/release cleanup
  API.Tests/Extensions/FileInfoExtensionsTests.cs
  API.Tests/Extensions/Test Data/modified on run.txt
  API.Tests/Extensions/Test Data/not modified.txt
  API.Tests/Parser/MangaParserTests.cs
  API.Tests/Services/ScannerServiceTests.cs
  API/Controllers/BookController.cs
  API/Controllers/DownloadController.cs
  API/Controllers/ReaderController.cs
  API/Controllers/SeriesController.cs
  API/Controllers/ServerController.cs
  API/DTOs/SeriesByIdsDto.cs
  API/Data/ChapterRepository.cs
  API/Data/Seed.cs
  API/Data/SeriesRepository.cs
  API/Data/VolumeRepository.cs
  API/Entities/AppUserProgress.cs
  API/Entities/CollectionTag.cs
  API/Extensions/DirectoryInfoExtensions.cs
  API/Extensions/FileInfoExtensions.cs
  API/Interfaces/Services/IVersionUpdaterService.cs
  API/Services/ArchiveService.cs
  API/Services/CacheService.cs
  API/Services/Clients/StatsApiClient.cs
  API/Services/DirectoryService.cs
  API/Services/MetadataService.cs
  API/Services/TaskScheduler.cs
  API/Services/Tasks/ScannerService.cs
  API/Services/Tasks/VersionUpdaterService.cs
  API/Startup.cs
  Kavita.Common/Configuration.cs
  Kavita.Common/KavitaException.cs
  UI/Web/src/app/app.component.ts
  UI/Web/src/app/series-detail/series-detail.component.ts
Labels: bug

#513 Prevent cover images showing as a series
  .github/workflows/sonar-scan.yml
  API.Tests/Parser/MangaParserTests.cs
  API/Parser/Parser.cs
Labels: bug

#514 Prevent cover images showing as a series
  .github/workflows/sonar-scan.yml
Labels: bug

#517 Cover generation issue on first scan flow
  API.Tests/Extensions/Test Data/modified on run.txt
  API.Tests/Services/MetadataServiceTests.cs
  API/Controllers/SeriesController.cs
  API/Entities/MangaFile.cs
  API/Extensions/FileInfoExtensions.cs
  API/Services/MetadataService.cs
  API/Services/Tasks/ScannerService.cs
Labels: bug, Scanner

#538 Add support for mangapy syntax to parser
  .gitignore
  API.Tests/Parser/MangaParserTests.cs
  API/Parser/Parser.cs
Labels: enhancement, Parser
