Repository Kareadita/Kavita, pull requests merged in 2021-07, with the labels that each got.

#375 Raw Image Support
  API.Tests/Services/BookServiceTests.cs
  API.Tests/Services/DirectoryServiceTests.cs
  API.Tests/Services/ScannerServiceTests.cs
  API/API.csproj
  API/Controllers/BookController.cs
  API/Controllers/SettingsController.cs
  API/Entities/Enums/LibraryType.cs
  API/Extensions/ApplicationServiceExtensions.cs
  API/Interfaces/Services/IArchiveService.cs
  API/Interfaces/Services/IBookService.cs
  API/Interfaces/Services/IDirectoryService.cs
  API/Interfaces/Services/IImageService.cs
  API/Parser/Parser.cs
  API/Services/ArchiveService.cs
  API/Services/BookService.cs
  API/Services/CacheService.cs
  API/Services/DirectoryService.cs
  API/Services/ImageService.cs
  API/Services/MetadataService.cs
  API/Services/Tasks/ScannerService.cs
  Kavita.Common/Extensions/EnumExtensions.cs
  Kavita.Common/Extensions/PathExtensions.cs
  Kavita.Common/Kavita.Common.csproj
  UI/Web/src/app/_models/library.ts
  UI/Web/src/app/admin/manage-library/manage-library.component.ts
Labels: enhancement

#394 About Section
  API.Tests/Parser/MangaParserTests.cs
  API/Controllers/ServerController.cs
  API/Parser/Parser.cs
  API/Services/StatsService.cs
  UI/Web/src/app/_services/server.service.ts
  UI/Web/src/app/admin/_models/server-info.ts
  UI/Web/src/app/admin/admin.module.ts
  UI/Web/src/app/admin/dashboard/dashboard.component.html
  UI/Web/src/app/admin/dashboard/dashboard.component.ts
  UI/Web/src/app/admin/manage-settings/manage-settings.component.html
  UI/Web/src/app/admin/manage-settings/manage-settings.component.scss
  UI/Web/src/app/admin/manage-system/manage-system.component.html
  UI/Web/src/app/admin/manage-system/manage-system.component.scss
  UI/Web/src/app/admin/manage-system/manage-system.component.ts
  UI/Web/src/app/manga-reader/manga-reader.component.ts
Labels: UI, enhancement

#397 Adding Additional Workflows and Actions
  .github/workflows/discord-release-msg.yml
  .github/workflows/monorepo-test.yml
  .github/workflows/nightly-docker.yml
  .github/workflows/sentry-map.yml
  .github/workflows/sentry-release.yml
  .github/workflows/sonar-scan.yml
  .github/workflows/stable-docker.yml
  Dockerfile
Labels: enhancement

#435 Bugfix/reader progress
  API/Controllers/ReaderController.cs
  API/Data/Seed.cs
  Dockerfile.alpine
  Dockerfile.arm
  Kavita.Common/Kavita.Common.csproj
  build_target.sh
Labels: bug

#445 Suppress max page error on bookmark api and just adjust the pages for …
  API/Controllers/ReaderController.cs
  Kavita.Common/Kavita.Common.csproj
Labels: bug

#447 Filtering Bugs
  API/Controllers/SeriesController.cs
  API/Data/SeriesRepository.cs
  API/Extensions/FilterDtoExtensions.cs
  API/Services/BookService.cs
  UI/Web/src/app/shared/card-detail-layout/card-detail-layout.component.html
  UI/Web/src/app/shared/card-detail-layout/card-detail-layout.component.ts
  UI/Web/src/styles.scss
Labels: bug

#452 Bugfix/in progress
  API/Controllers/SeriesController.cs
  API/Data/SeriesRepository.cs
  API/Extensions/FilterDtoExtensions.cs
  API/Interfaces/ISeriesRepository.cs
  Kavita.Common/Kavita.Common.csproj
Labels: bug

#453 Fixed the In progress API returning back series that didn't belong
  .github/workflows/nightly-docker.yml
  API/Data/SeriesRepository.cs
  Kavita.Common/Kavita.Common.csproj
Labels: bug
