Repository Kareadita/Kavita, pull requests merged in 2022-01, with the labels that each got.

#935 Fix image aspect ratio when image has inline style
  UI/Web/src/app/book-reader/book-reader/book-reader.component.scss
Labels: bug

#961 Fullscreen keybind
  UI/Web/src/app/book-reader/book-reader/book-reader.component.ts
  UI/Web/src/app/manga-reader/manga-reader.component.ts
  UI/Web/src/app/shared/_services/utility.service.ts
Labels: enhancement

#962 Fix for 3rd Party Clients copy button
  UI/Web/src/app/user-settings/api-key/api-key.component.ts
Labels: bug

#987 Comics should show volumes tab
  UI/Web/src/app/series-detail/series-detail.component.html
Labels: bug

#984 Library page resetting
  UI/Web/src/app/library-detail/library-detail.component.ts
Labels: bug

#991 Fixed Parser.Parser.Normalize returns empty string
  API.Tests/Parser/ParserTest.cs
  API/Parser/Parser.cs
Labels: bug, Parser

#992 Fixes filter application
  API/Controllers/PluginController.cs
  API/Controllers/ReaderController.cs
  UI/Web/src/app/_models/series-filter.ts
  UI/Web/src/app/all-series/all-series.component.ts
  UI/Web/src/app/cards/card-detail-layout/card-detail-layout.component.ts
  UI/Web/src/app/collections/collection-detail/collection-detail.component.ts
  UI/Web/src/app/library-detail/library-detail.component.ts
  UI/Web/src/app/on-deck/on-deck.component.ts
  UI/Web/src/app/recently-added/recently-added.component.ts
Labels: bug

#990 Fix for add to collection visibility issue
  UI/Web/src/app/_services/action.service.ts
  UI/Web/src/app/cards/_modals/bulk-add-to-collection/bulk-add-to-collection.component.scss
  UI/Web/src/app/cards/_modals/bulk-add-to-collection/bulk-add-to-collection.component.ts
Labels: bug, UI

#1007 Recently Added Chapters/Volumes
  API/Controllers/SeriesController.cs
  API/DTOs/RecentlyAddedItemDto.cs
  API/Data/Repositories/SeriesRepository.cs
  UI/Web/src/app/_models/in-progress-chapter.ts
  UI/Web/src/app/_models/recently-added-item.ts
  UI/Web/src/app/_services/image.service.ts
  UI/Web/src/app/_services/series.service.ts
  UI/Web/src/app/cards/card-item/card-item.component.html
  UI/Web/src/app/cards/card-item/card-item.component.ts
  UI/Web/src/app/library/library.component.html
  UI/Web/src/app/library/library.component.ts
Labels: enhancement

#1012 Book series tab fix
  UI/Web/src/app/series-detail/series-detail.component.ts
Labels: bug
